### ISSUE TITLE
Create a X-Plattform install prerequisite for the python environment and packages

### ISSUE THREAD

**Issue by Christian-Mielke** [UBA-DE-Emissionsituation/space-emissions#18]
If we could write a nice install script for everybody using mambaforge here:

https://github.com/conda-forge/miniforge#mambaforge

that would be very handy. Please note that X-Platform compatibility is at the expense of the exact version definition of each package. Maybe creating the file manually, with just a few entries as in the docs example is fair enough as the dependencies for the key packages will be installed alongside anyway.

**Comment by jptokaya** [comment]
I'll look into this one, but never used mamba. What is the benefit compared to conda for example?

**Comment by Christian-Mielke** [comment]
Hi Janot, 
I think the most difference is that it is "lightweight" it does only install what you really need compared to a full blown installation of Anaconda Python. Then it is also faster (as they claim) than the "standard" Conda. I would say this is very interesting also because there are potions for PPC and ARM Systems.

**Comment by Christian-Mielke** [comment]
If you run this in your mamba console you should be good to go (maybe also trying a more recent Python version such as above 3.6)

mamba create -n Python36 python=3.6
conda activate Python36
mamba install h5py spyder gdal geopandas ipython-sql sentinelsat spectral pykrige opencv scikit-learn scikit-image jupyterlab notebook -c conda-forge

**Comment by kevin-hausmann** [comment]
I think we should look at pipenv, this seems to be the correct approach, see https://pipenv.pypa.io/en/latest/ and https://www.youtube.com/watch?v=GBQAKldqgZs

**Comment by kevin-hausmann** [comment]
Decided to use mambaforge, closed by #29
